// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponse_Status int32

const (
	BidResponse_FAIL      BidResponse_Status = 0
	BidResponse_SUCCESS   BidResponse_Status = 1
	BidResponse_EXCEPTION BidResponse_Status = 2
)

// Enum value maps for BidResponse_Status.
var (
	BidResponse_Status_name = map[int32]string{
		0: "FAIL",
		1: "SUCCESS",
		2: "EXCEPTION",
	}
	BidResponse_Status_value = map[string]int32{
		"FAIL":      0,
		"SUCCESS":   1,
		"EXCEPTION": 2,
	}
)

func (x BidResponse_Status) Enum() *BidResponse_Status {
	p := new(BidResponse_Status)
	*p = x
	return p
}

func (x BidResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_enumTypes[0].Descriptor()
}

func (BidResponse_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_enumTypes[0]
}

func (x BidResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidResponse_Status.Descriptor instead.
func (BidResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{1, 0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        BidResponse_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=auction.BidResponse_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetStatus() BidResponse_Status {
	if x != nil {
		return x.Status
	}
	return BidResponse_FAIL
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_pb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{2}
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      bool                   `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	HighestBidder string                 `protobuf:"bytes,2,opt,name=highestBidder,proto3" json:"highestBidder,omitempty"`
	HighestAmount int64                  `protobuf:"varint,3,opt,name=highestAmount,proto3" json:"highestAmount,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_pb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ResultResponse) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *ResultResponse) GetHighestAmount() int64 {
	if x != nil {
		return x.HighestAmount
	}
	return 0
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReplicateBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bidder        string                 `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBidRequest) Reset() {
	*x = ReplicateBidRequest{}
	mi := &file_pb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidRequest) ProtoMessage() {}

func (x *ReplicateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidRequest.ProtoReflect.Descriptor instead.
func (*ReplicateBidRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateBidRequest) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

func (x *ReplicateBidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReplicateBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBidResponse) Reset() {
	*x = ReplicateBidResponse{}
	mi := &file_pb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidResponse) ProtoMessage() {}

func (x *ReplicateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidResponse.ProtoReflect.Descriptor instead.
func (*ReplicateBidResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicateBidResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pb_proto protoreflect.FileDescriptor

const file_pb_proto_rawDesc = "" +
	"\n" +
	"\bpb.proto\x12\aauction\"<\n" +
	"\n" +
	"BidRequest\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\x8c\x01\n" +
	"\vBidResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.auction.BidResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x06Status\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\"\x0f\n" +
	"\rResultRequest\"\x92\x01\n" +
	"\x0eResultResponse\x12\x1a\n" +
	"\bfinished\x18\x01 \x01(\bR\bfinished\x12$\n" +
	"\rhighestBidder\x18\x02 \x01(\tR\rhighestBidder\x12$\n" +
	"\rhighestAmount\x18\x03 \x01(\x03R\rhighestAmount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"E\n" +
	"\x13ReplicateBidRequest\x12\x16\n" +
	"\x06bidder\x18\x01 \x01(\tR\x06bidder\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"&\n" +
	"\x14ReplicateBidResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xca\x01\n" +
	"\x0eAuctionService\x120\n" +
	"\x03Bid\x12\x13.auction.BidRequest\x1a\x14.auction.BidResponse\x129\n" +
	"\x06Result\x12\x16.auction.ResultRequest\x1a\x17.auction.ResultResponse\x12K\n" +
	"\fReplicateBid\x12\x1c.auction.ReplicateBidRequest\x1a\x1d.auction.ReplicateBidResponseB\x0fZ\rhandin5/pb;pbb\x06proto3"

var (
	file_pb_proto_rawDescOnce sync.Once
	file_pb_proto_rawDescData []byte
)

func file_pb_proto_rawDescGZIP() []byte {
	file_pb_proto_rawDescOnce.Do(func() {
		file_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_proto_rawDesc), len(file_pb_proto_rawDesc)))
	})
	return file_pb_proto_rawDescData
}

var file_pb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_proto_goTypes = []any{
	(BidResponse_Status)(0),      // 0: auction.BidResponse.Status
	(*BidRequest)(nil),           // 1: auction.BidRequest
	(*BidResponse)(nil),          // 2: auction.BidResponse
	(*ResultRequest)(nil),        // 3: auction.ResultRequest
	(*ResultResponse)(nil),       // 4: auction.ResultResponse
	(*ReplicateBidRequest)(nil),  // 5: auction.ReplicateBidRequest
	(*ReplicateBidResponse)(nil), // 6: auction.ReplicateBidResponse
}
var file_pb_proto_depIdxs = []int32{
	0, // 0: auction.BidResponse.status:type_name -> auction.BidResponse.Status
	1, // 1: auction.AuctionService.Bid:input_type -> auction.BidRequest
	3, // 2: auction.AuctionService.Result:input_type -> auction.ResultRequest
	5, // 3: auction.AuctionService.ReplicateBid:input_type -> auction.ReplicateBidRequest
	2, // 4: auction.AuctionService.Bid:output_type -> auction.BidResponse
	4, // 5: auction.AuctionService.Result:output_type -> auction.ResultResponse
	6, // 6: auction.AuctionService.ReplicateBid:output_type -> auction.ReplicateBidResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_proto_init() }
func file_pb_proto_init() {
	if File_pb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_proto_rawDesc), len(file_pb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_goTypes,
		DependencyIndexes: file_pb_proto_depIdxs,
		EnumInfos:         file_pb_proto_enumTypes,
		MessageInfos:      file_pb_proto_msgTypes,
	}.Build()
	File_pb_proto = out.File
	file_pb_proto_goTypes = nil
	file_pb_proto_depIdxs = nil
}
